name: Build documents
on: 
  push:
    branches:
      master
jobs:
  build_cv:
    name: Build CV
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile CV
        id: compile
        uses: tcibinan/build-latex-already@0.1.4
        with:
          tex: cv.tex
      - name: Tag latest commit
        uses: tvdias/github-tagger@v0.0.2
        with:
          tag: ${{ github.run_id }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish pelease
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.run_id }}
          files: ${{ steps.compile.outputs.pdf }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
