name: Build documents
on: 
  push:
    branches:
      master
jobs:
  build_cv:
    name: Build CV
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile CV
        uses: tcibinan/build-latex-already@0.1.1
        with:
          tex: 'cv.tex'
        id: compile
      - name: Publish pelease
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.compile.outputs.pdf }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
